index:
    path: /
    controller: App\Controller\PersonController::new

app_public_files:
  path: /uploads/files/{filename}
  controller: App\Controller\PersonController::show

app_login:
  path: /login
  controller: App\Controller\LoginController::login